### ISSUE TITLE
clone-all does not work

### ISSUE THREAD

**Issue by totoroha** [silky/clone-all#2]
This is the error i got:
cabal install clone-all-0.1.0.0
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: clone-all-0.1.0.0 (user goal)
trying: github-0.15.0 (dependency of clone-all-0.1.0.0)
trying: vector-instances-3.4 (dependency of github-0.15.0)
trying: keys-3.11 (dependency of vector-instances-3.4)
trying: free-4.12.4 (dependency of keys-3.11)
trying: profunctors-5.2 (dependency of free-4.12.4)
trying: tagged-0.8.5 (dependency of profunctors-5.2)
trying: vector-0.12.0.1 (dependency of github-0.15.0)
trying: semigroups-0.18.3 (dependency of github-0.15.0)
trying: http-link-header-1.0.3 (dependency of github-0.15.0)
trying: attoparsec-0.13.1.0 (dependency of http-link-header-1.0.3)
trying: scientific-0.3.4.15 (dependency of attoparsec-0.13.1.0)
next goal: binary-orphans (dependency of github-0.15.0)
rejecting: binary-orphans-0.1.6.0, 0.1.5.2 (conflict: semigroups==0.18.3,
binary-orphans => semigroups>=0.16.2.2 && <0.18.3)
rejecting: binary-orphans-0.1.5.1 (conflict: vector==0.12.0.1, binary-orphans
=> vector>=0.10.12.3 && <0.12)
rejecting: binary-orphans-0.1.5.0 (conflict: tagged==0.8.5, binary-orphans =>
tagged>=0.7.3 && <0.8.5)
rejecting: binary-orphans-0.1.4.0 (conflict: semigroups==0.18.3,
binary-orphans => semigroups>=0.16.2.2 && <0.18.2)
rejecting: binary-orphans-0.1.3.0 (conflict: semigroups==0.18.3,
binary-orphans => semigroups>=0.16 && <0.18.1)
rejecting: binary-orphans-0.1.2.0 (conflict: tagged==0.8.5, binary-orphans =>
tagged>=0.7 && <0.8.3)
rejecting: binary-orphans-0.1.1.0, 0.1.0.0 (conflict: scientific==0.3.4.15,
binary-orphans => scientific>=0.3 && <0.3.4)
Backjump limit reached (change with --max-backjumps).

**Comment by silky** [comment]
thanks for the report!

i've uploaded a stack file, so now you can build it by cloning it locally and running `stack install` :)

let me know if that doesn't work :)
